name: theme_changed_event
description: An example of Theme Switching using the Flutter Bus.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bus:
    git: git@github.com:michaelbushe/flutter_bus.git
  mindful_flutter_util:
    path: ../../
  mindful_flutter_themes:
    git: git@github.com:michaelbushe/mindful_material3_themes.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true