name: mindful_flutter_util
description: Utilities for Flutter from Mindful Software.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  flex_color_scheme: ^6.1.2
  flex_color_picker: ^2.5.0
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  intl: ^0.17.0
  mindful_dart_util:
    git: git@github.com:michaelbushe/mindful_dart_util.git
  package_info_plus: ^2.0.0
  path_provider: ^2.0.11
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

