name: mindful_flutter_util
description: Utilities for Flutter from Mindful Software.
repository: https://github.com/michaelbushe/mindful_flutter_util
version: 0.13.0-dev.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  card_loading: ^0.3.2
  catcher: ^1.0.0-dev1
  chips_choice: ^3.0.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  cupertino_icons: ^1.0.8
  currency_picker: ^2.0.21
  device_info_plus: ^10.1.0
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0
  firebase_ui_oauth: ^1.6.0
  firebase_ui_oauth_google: ^1.4.0
  flutter_bloc: ^8.1.6
  flutter_bus: ^0.5.0+4
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.3
  flutter_shimmer: ^2.1.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  geolocator: ^13.0.1
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  #for dynamic_widget font_awesome_flutter:  ^9.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  #  mindful_dart_util: ^0.9.0
  mindful_dart_util:
    path: ../mindful_dart_util
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  #  mindful_pluto_grid_util:
  #    git: git@github.com:MindfulSoftwareLLC/mindful_pluto_grid_util.git
  pluto_grid_plus: ^8.4.2
  provider: ^6.1.2
  rxdart: ^0.28.0
  select2dot1: ^2.0.9
  shared_preferences: ^2.3.2
  shimmer_animation: ^2.2.1
  string_scanner: ^1.2.0
  url_launcher: ^6.3.0
  validators: ^3.0.0

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  mindful_analysis: ^1.0.0+2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/src/no_wonder/logic/common/


