name: mindful_flutter_util
description: Utilities for Flutter from Mindful Software.
repository: https://github.com/michaelbushe/mindful_flutter_util
version: 0.11.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3
  flex_color_scheme: ^7.3.1
  flex_color_picker: ^3.4.1
  flutter_bloc: ^8.1.5
  flutter_bus: ^0.5.0+4

  font_awesome_flutter: ^10.7.0
  #for dynamic_widget font_awesome_flutter:  ^9.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
#  mindful_dart_util: ^0.7.1
  mindful_dart_util:
    path: ../mindful_dart_util
  package_info_plus: ^7.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  string_scanner: ^1.2.0
  url_launcher: ^6.2.6

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  mindful_analysis: ^1.0.0+2

flutter:
  uses-material-design: true
  generate: true

