name: mindful_flutter_util
description: Utilities for Flutter from Mindful Software.
repository: https://github.com/michaelbushe/mindful_flutter_util
version: 0.5.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.1
  dynamic_color: ^1.6.2
  flex_color_scheme: ^6.1.2
  flex_color_picker: ^3.1.0
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  intl: ^0.17.0
  mindful_dart_util:
    path: ../dart_util
#    git: git@github.com:michaelbushe/mindful_dart_util.git
  package_info_plus: ^3.0.3
  path_provider: ^2.0.12
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true

